# Generated by Django 4.1.3 on 2024-10-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fraud_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Flagged', 'Flagged')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='transaction_id',
            field=models.CharField(default='default_id', max_length=50, unique=True),
        ),
    ]
