# Generated by Django 4.1.3 on 2024-10-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_fraud_score_report_is_flagged_report_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='report',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
