services:
  - type: web
    name: fraud-detection-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backendML && gunicorn backendML.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: fraud_detection_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: fraud_detection_db
    databaseName: fraud_detection
    plan: free
