# Generated by Django 5.1.3 on 2024-11-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('tender_title', models.CharField(max_length=255)),
                ('eval_completion_date', models.DateField(blank=True, null=True)),
                ('notification_of_award_date', models.DateField(blank=True, null=True)),
                ('sign_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('agpo_certificate_number', models.CharField(max_length=255)),
                ('awarded_agpo_group_id', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('terminated', models.BooleanField(default=False)),
                ('financial_year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('tender_ref', models.CharField(max_length=255)),
                ('pe_name', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('no_of_boi', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
